// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type AlgorithmSpecification struct {
	AlgorithmName                    *string `json:"algorithmName,omitempty"`
	EnableSageMakerMetricsTimeSeries *bool   `json:"enableSageMakerMetricsTimeSeries,omitempty"`
}

type AlgorithmValidationSpecification struct {
	ValidationRole *string `json:"validationRole,omitempty"`
}

type AutoMLCandidate struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	EndTime          *metav1.Time `json:"endTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type AutoMLContainerDefinition struct {
	Environment  map[string]*string `json:"environment,omitempty"`
	Image        *string            `json:"image,omitempty"`
	ModelDataURL *string            `json:"modelDataURL,omitempty"`
}

type AutoMLJobSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	EndTime          *metav1.Time `json:"endTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type AutoMLSecurityConfig struct {
	EnableInterContainerTrafficEncryption *bool      `json:"enableInterContainerTrafficEncryption,omitempty"`
	VPCConfig                             *VPCConfig `json:"vpcConfig,omitempty"`
}

type ChannelSpecification struct {
	IsRequired *bool `json:"isRequired,omitempty"`
}

type CompilationJobSummary struct {
	CompilationEndTime   *metav1.Time `json:"compilationEndTime,omitempty"`
	CompilationStartTime *metav1.Time `json:"compilationStartTime,omitempty"`
}

type ContainerDefinition struct {
	ContainerHostname *string            `json:"containerHostname,omitempty"`
	Environment       map[string]*string `json:"environment,omitempty"`
	Image             *string            `json:"image,omitempty"`
	ImageConfig       *ImageConfig       `json:"imageConfig,omitempty"`
	Mode              *string            `json:"mode,omitempty"`
	ModelDataURL      *string            `json:"modelDataURL,omitempty"`
	ModelPackageName  *string            `json:"modelPackageName,omitempty"`
}

type DebugRuleEvaluationStatus struct {
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type DeployedImage struct {
	ResolutionTime *metav1.Time `json:"resolutionTime,omitempty"`
	ResolvedImage  *string      `json:"resolvedImage,omitempty"`
	SpecifiedImage *string      `json:"specifiedImage,omitempty"`
}

type EndpointConfigSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

type EndpointSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type Experiment struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	Tags             []*Tag       `json:"tags,omitempty"`
}

type ExperimentSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type FlowDefinitionSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

type HumanTaskUiSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

type HyperParameterAlgorithmSpecification struct {
	AlgorithmName *string `json:"algorithmName,omitempty"`
}

type HyperParameterSpecification struct {
	IsRequired *bool `json:"isRequired,omitempty"`
	IsTunable  *bool `json:"isTunable,omitempty"`
}

type HyperParameterTrainingJobDefinition struct {
	EnableInterContainerTrafficEncryption *bool      `json:"enableInterContainerTrafficEncryption,omitempty"`
	EnableManagedSpotTraining             *bool      `json:"enableManagedSpotTraining,omitempty"`
	EnableNetworkIsolation                *bool      `json:"enableNetworkIsolation,omitempty"`
	RoleARN                               *string    `json:"roleARN,omitempty"`
	VPCConfig                             *VPCConfig `json:"vpcConfig,omitempty"`
}

type HyperParameterTrainingJobSummary struct {
	CreationTime      *metav1.Time `json:"creationTime,omitempty"`
	TrainingEndTime   *metav1.Time `json:"trainingEndTime,omitempty"`
	TrainingStartTime *metav1.Time `json:"trainingStartTime,omitempty"`
}

type HyperParameterTuningJobSummary struct {
	CreationTime                *metav1.Time `json:"creationTime,omitempty"`
	HyperParameterTuningEndTime *metav1.Time `json:"hyperParameterTuningEndTime,omitempty"`
	LastModifiedTime            *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type ImageConfig struct {
	RepositoryAccessMode *string `json:"repositoryAccessMode,omitempty"`
}

type LabelingJobAlgorithmsConfig struct {
	InitialActiveLearningModelARN *string `json:"initialActiveLearningModelARN,omitempty"`
}

type LabelingJobForWorkteamSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

type LabelingJobOutput struct {
	FinalActiveLearningModelARN *string `json:"finalActiveLearningModelARN,omitempty"`
}

type LabelingJobSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type MetricData struct {
	Timestamp *metav1.Time `json:"timestamp,omitempty"`
}

type ModelPackageContainerDefinition struct {
	ContainerHostname *string `json:"containerHostname,omitempty"`
	Image             *string `json:"image,omitempty"`
	ModelDataURL      *string `json:"modelDataURL,omitempty"`
}

type ModelPackageValidationSpecification struct {
	ValidationRole *string `json:"validationRole,omitempty"`
}

type ModelSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	ModelARN     *string      `json:"modelARN,omitempty"`
	ModelName    *string      `json:"modelName,omitempty"`
}

type MonitoringExecutionSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	ScheduledTime    *metav1.Time `json:"scheduledTime,omitempty"`
}

type MonitoringJobDefinition struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

type MonitoringScheduleSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type NetworkConfig struct {
	EnableInterContainerTrafficEncryption *bool      `json:"enableInterContainerTrafficEncryption,omitempty"`
	EnableNetworkIsolation                *bool      `json:"enableNetworkIsolation,omitempty"`
	VPCConfig                             *VPCConfig `json:"vpcConfig,omitempty"`
}

type ProcessingJob struct {
	CreationTime        *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime    *metav1.Time `json:"lastModifiedTime,omitempty"`
	ProcessingEndTime   *metav1.Time `json:"processingEndTime,omitempty"`
	ProcessingStartTime *metav1.Time `json:"processingStartTime,omitempty"`
	RoleARN             *string      `json:"roleARN,omitempty"`
	Tags                []*Tag       `json:"tags,omitempty"`
}

type ProcessingJobSummary struct {
	CreationTime      *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime  *metav1.Time `json:"lastModifiedTime,omitempty"`
	ProcessingEndTime *metav1.Time `json:"processingEndTime,omitempty"`
}

type ProductionVariant struct {
	ModelName *string `json:"modelName,omitempty"`
}

type SecondaryStatusTransition struct {
	EndTime   *metav1.Time `json:"endTime,omitempty"`
	StartTime *metav1.Time `json:"startTime,omitempty"`
}

type SourceAlgorithm struct {
	AlgorithmName *string `json:"algorithmName,omitempty"`
	ModelDataURL  *string `json:"modelDataURL,omitempty"`
}

type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type TrainingJob struct {
	CreationTime                          *metav1.Time `json:"creationTime,omitempty"`
	EnableInterContainerTrafficEncryption *bool        `json:"enableInterContainerTrafficEncryption,omitempty"`
	EnableManagedSpotTraining             *bool        `json:"enableManagedSpotTraining,omitempty"`
	EnableNetworkIsolation                *bool        `json:"enableNetworkIsolation,omitempty"`
	LastModifiedTime                      *metav1.Time `json:"lastModifiedTime,omitempty"`
	RoleARN                               *string      `json:"roleARN,omitempty"`
	Tags                                  []*Tag       `json:"tags,omitempty"`
	TrainingEndTime                       *metav1.Time `json:"trainingEndTime,omitempty"`
	TrainingStartTime                     *metav1.Time `json:"trainingStartTime,omitempty"`
	VPCConfig                             *VPCConfig   `json:"vpcConfig,omitempty"`
}

type TrainingJobSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	TrainingEndTime  *metav1.Time `json:"trainingEndTime,omitempty"`
}

type TrainingSpecification struct {
	SupportsDistributedTraining *bool   `json:"supportsDistributedTraining,omitempty"`
	TrainingImage               *string `json:"trainingImage,omitempty"`
}

type TransformJob struct {
	CreationTime       *metav1.Time `json:"creationTime,omitempty"`
	ModelName          *string      `json:"modelName,omitempty"`
	Tags               []*Tag       `json:"tags,omitempty"`
	TransformEndTime   *metav1.Time `json:"transformEndTime,omitempty"`
	TransformStartTime *metav1.Time `json:"transformStartTime,omitempty"`
}

type TransformJobSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	TransformEndTime *metav1.Time `json:"transformEndTime,omitempty"`
}

type Trial struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	Tags             []*Tag       `json:"tags,omitempty"`
}

type TrialComponent struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	EndTime          *metav1.Time `json:"endTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	StartTime        *metav1.Time `json:"startTime,omitempty"`
	Tags             []*Tag       `json:"tags,omitempty"`
}

type TrialComponentMetricSummary struct {
	TimeStamp *metav1.Time `json:"timeStamp,omitempty"`
}

type TrialComponentSimpleSummary struct {
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
}

type TrialComponentSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	EndTime          *metav1.Time `json:"endTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
	StartTime        *metav1.Time `json:"startTime,omitempty"`
}

type TrialSummary struct {
	CreationTime     *metav1.Time `json:"creationTime,omitempty"`
	LastModifiedTime *metav1.Time `json:"lastModifiedTime,omitempty"`
}

type UserSettings struct {
	ExecutionRole *string `json:"executionRole,omitempty"`
}

type VPCConfig struct {
	SecurityGroupIDs []*string `json:"securityGroupIDs,omitempty"`
	Subnets          []*string `json:"subnets,omitempty"`
}

type Workforce struct {
	CreateDate      *metav1.Time `json:"createDate,omitempty"`
	LastUpdatedDate *metav1.Time `json:"lastUpdatedDate,omitempty"`
}

type Workteam struct {
	CreateDate      *metav1.Time `json:"createDate,omitempty"`
	LastUpdatedDate *metav1.Time `json:"lastUpdatedDate,omitempty"`
}
