// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type BatchResultErrorEntry struct {
	Code    *string `json:"code,omitempty"`
	ID      *string `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

type ChangeMessageVisibilityBatchRequestEntry struct {
	ID            *string `json:"id,omitempty"`
	ReceiptHandle *string `json:"receiptHandle,omitempty"`
}

type ChangeMessageVisibilityBatchResultEntry struct {
	ID *string `json:"id,omitempty"`
}

type DeleteMessageBatchRequestEntry struct {
	ID            *string `json:"id,omitempty"`
	ReceiptHandle *string `json:"receiptHandle,omitempty"`
}

type DeleteMessageBatchResultEntry struct {
	ID *string `json:"id,omitempty"`
}

type Message struct {
	Body                   *string `json:"body,omitempty"`
	MD5OfBody              *string `json:"md5OfBody,omitempty"`
	MD5OfMessageAttributes *string `json:"md5OfMessageAttributes,omitempty"`
	MessageID              *string `json:"messageID,omitempty"`
	ReceiptHandle          *string `json:"receiptHandle,omitempty"`
}

type MessageAttributeValue struct {
	DataType    *string `json:"dataType,omitempty"`
	StringValue *string `json:"stringValue,omitempty"`
}

type MessageSystemAttributeValue struct {
	DataType    *string `json:"dataType,omitempty"`
	StringValue *string `json:"stringValue,omitempty"`
}

type SendMessageBatchRequestEntry struct {
	ID                     *string `json:"id,omitempty"`
	MessageBody            *string `json:"messageBody,omitempty"`
	MessageDeduplicationID *string `json:"messageDeduplicationID,omitempty"`
	MessageGroupID         *string `json:"messageGroupID,omitempty"`
}

type SendMessageBatchResultEntry struct {
	ID                           *string `json:"id,omitempty"`
	MD5OfMessageAttributes       *string `json:"md5OfMessageAttributes,omitempty"`
	MD5OfMessageBody             *string `json:"md5OfMessageBody,omitempty"`
	MD5OfMessageSystemAttributes *string `json:"md5OfMessageSystemAttributes,omitempty"`
	MessageID                    *string `json:"messageID,omitempty"`
	SequenceNumber               *string `json:"sequenceNumber,omitempty"`
}
