// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws/aws-controllers-k8s/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// IntegrationResponseSpec defines the desired state of IntegrationResponse
type IntegrationResponseSpec struct {
	// +kubebuilder:validation:Required
	APIID                   *string `json:"apiID"`
	ContentHandlingStrategy *string `json:"contentHandlingStrategy,omitempty"`
	// +kubebuilder:validation:Required
	IntegrationID *string `json:"integrationID"`
	// +kubebuilder:validation:Required
	IntegrationResponseKey      *string            `json:"integrationResponseKey"`
	ResponseParameters          map[string]*string `json:"responseParameters,omitempty"`
	ResponseTemplates           map[string]*string `json:"responseTemplates,omitempty"`
	TemplateSelectionExpression *string            `json:"templateSelectionExpression,omitempty"`
}

// IntegrationResponseStatus defines the observed state of IntegrationResponse
type IntegrationResponseStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	Conditions            []*ackv1alpha1.Condition `json:"conditions"`
	IntegrationResponseID *string                  `json:"integrationResponseID,omitempty"`
}

// IntegrationResponse is the Schema for the IntegrationResponses API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type IntegrationResponse struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              IntegrationResponseSpec   `json:"spec,omitempty"`
	Status            IntegrationResponseStatus `json:"status,omitempty"`
}

// IntegrationResponseList contains a list of IntegrationResponse
// +kubebuilder:object:root=true
type IntegrationResponseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IntegrationResponse `json:"items"`
}

func init() {
	SchemeBuilder.Register(&IntegrationResponse{}, &IntegrationResponseList{})
}
