---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-sagemaker-writer
  namespace: default
rules:
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models
  - trainingjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sagemaker.services.k8s.aws
  resources:
  - models
  - trainingjobs
  verbs:
  - get
  - patch
  - update
