// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type EventSourcePosition string

const (
	EventSourcePosition_TRIM_HORIZON EventSourcePosition = "TRIM_HORIZON"
	EventSourcePosition_LATEST       EventSourcePosition = "LATEST"
	EventSourcePosition_AT_TIMESTAMP EventSourcePosition = "AT_TIMESTAMP"
)

type FunctionVersion string

const (
	FunctionVersion_ALL FunctionVersion = "ALL"
)

type InvocationType string

const (
	InvocationType_Event           InvocationType = "Event"
	InvocationType_RequestResponse InvocationType = "RequestResponse"
	InvocationType_DryRun          InvocationType = "DryRun"
)

type LastUpdateStatus string

const (
	LastUpdateStatus_Successful LastUpdateStatus = "Successful"
	LastUpdateStatus_Failed     LastUpdateStatus = "Failed"
	LastUpdateStatus_InProgress LastUpdateStatus = "InProgress"
)

type LastUpdateStatusReasonCode string

const (
	LastUpdateStatusReasonCode_EniLimitExceeded            LastUpdateStatusReasonCode = "EniLimitExceeded"
	LastUpdateStatusReasonCode_InsufficientRolePermissions LastUpdateStatusReasonCode = "InsufficientRolePermissions"
	LastUpdateStatusReasonCode_InvalidConfiguration        LastUpdateStatusReasonCode = "InvalidConfiguration"
	LastUpdateStatusReasonCode_InternalError               LastUpdateStatusReasonCode = "InternalError"
	LastUpdateStatusReasonCode_SubnetOutOfIPAddresses      LastUpdateStatusReasonCode = "SubnetOutOfIPAddresses"
	LastUpdateStatusReasonCode_InvalidSubnet               LastUpdateStatusReasonCode = "InvalidSubnet"
	LastUpdateStatusReasonCode_InvalidSecurityGroup        LastUpdateStatusReasonCode = "InvalidSecurityGroup"
)

type LogType string

const (
	LogType_None LogType = "None"
	LogType_Tail LogType = "Tail"
)

type ProvisionedConcurrencyStatusEnum string

const (
	ProvisionedConcurrencyStatusEnum_IN_PROGRESS ProvisionedConcurrencyStatusEnum = "IN_PROGRESS"
	ProvisionedConcurrencyStatusEnum_READY       ProvisionedConcurrencyStatusEnum = "READY"
	ProvisionedConcurrencyStatusEnum_FAILED      ProvisionedConcurrencyStatusEnum = "FAILED"
)

type Runtime string

const (
	Runtime_nodejs         Runtime = "nodejs"
	Runtime_nodejs4_3      Runtime = "nodejs4.3"
	Runtime_nodejs6_10     Runtime = "nodejs6.10"
	Runtime_nodejs8_10     Runtime = "nodejs8.10"
	Runtime_nodejs10_x     Runtime = "nodejs10.x"
	Runtime_nodejs12_x     Runtime = "nodejs12.x"
	Runtime_java8          Runtime = "java8"
	Runtime_java8_al2      Runtime = "java8.al2"
	Runtime_java11         Runtime = "java11"
	Runtime_python2_7      Runtime = "python2.7"
	Runtime_python3_6      Runtime = "python3.6"
	Runtime_python3_7      Runtime = "python3.7"
	Runtime_python3_8      Runtime = "python3.8"
	Runtime_dotnetcore1_0  Runtime = "dotnetcore1.0"
	Runtime_dotnetcore2_0  Runtime = "dotnetcore2.0"
	Runtime_dotnetcore2_1  Runtime = "dotnetcore2.1"
	Runtime_dotnetcore3_1  Runtime = "dotnetcore3.1"
	Runtime_nodejs4_3_edge Runtime = "nodejs4.3-edge"
	Runtime_go1_x          Runtime = "go1.x"
	Runtime_ruby2_5        Runtime = "ruby2.5"
	Runtime_ruby2_7        Runtime = "ruby2.7"
	Runtime_provided       Runtime = "provided"
	Runtime_provided_al2   Runtime = "provided.al2"
)

type State string

const (
	State_Pending  State = "Pending"
	State_Active   State = "Active"
	State_Inactive State = "Inactive"
	State_Failed   State = "Failed"
)

type StateReasonCode string

const (
	StateReasonCode_Idle                        StateReasonCode = "Idle"
	StateReasonCode_Creating                    StateReasonCode = "Creating"
	StateReasonCode_Restoring                   StateReasonCode = "Restoring"
	StateReasonCode_EniLimitExceeded            StateReasonCode = "EniLimitExceeded"
	StateReasonCode_InsufficientRolePermissions StateReasonCode = "InsufficientRolePermissions"
	StateReasonCode_InvalidConfiguration        StateReasonCode = "InvalidConfiguration"
	StateReasonCode_InternalError               StateReasonCode = "InternalError"
	StateReasonCode_SubnetOutOfIPAddresses      StateReasonCode = "SubnetOutOfIPAddresses"
	StateReasonCode_InvalidSubnet               StateReasonCode = "InvalidSubnet"
	StateReasonCode_InvalidSecurityGroup        StateReasonCode = "InvalidSecurityGroup"
)

type ThrottleReason string

const (
	ThrottleReason_ConcurrentInvocationLimitExceeded                 ThrottleReason = "ConcurrentInvocationLimitExceeded"
	ThrottleReason_FunctionInvocationRateLimitExceeded               ThrottleReason = "FunctionInvocationRateLimitExceeded"
	ThrottleReason_ReservedFunctionConcurrentInvocationLimitExceeded ThrottleReason = "ReservedFunctionConcurrentInvocationLimitExceeded"
	ThrottleReason_ReservedFunctionInvocationRateLimitExceeded       ThrottleReason = "ReservedFunctionInvocationRateLimitExceeded"
	ThrottleReason_CallerRateLimitExceeded                           ThrottleReason = "CallerRateLimitExceeded"
)

type TracingMode string

const (
	TracingMode_Active      TracingMode = "Active"
	TracingMode_PassThrough TracingMode = "PassThrough"
)
