// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type Endpoint struct {
	Attributes  map[string]*string `json:"attributes,omitempty"`
	EndpointARN *string            `json:"endpointARN,omitempty"`
}

type MessageAttributeValue struct {
	DataType    *string `json:"dataType,omitempty"`
	StringValue *string `json:"stringValue,omitempty"`
}

type PlatformApplication_SDK struct {
	Attributes             map[string]*string `json:"attributes,omitempty"`
	PlatformApplicationARN *string            `json:"platformApplicationARN,omitempty"`
}

type Subscription struct {
	TopicARN *string `json:"topicARN,omitempty"`
}

type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type Topic_SDK struct {
	TopicARN *string `json:"topicARN,omitempty"`
}
