// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

type ActivityListItem struct {
	ActivityARN  *string      `json:"activityARN,omitempty"`
	CreationDate *metav1.Time `json:"creationDate,omitempty"`
	Name         *string      `json:"name,omitempty"`
}

type ActivityScheduledEventDetails struct {
	Resource *string `json:"resource,omitempty"`
}

type CloudWatchLogsLogGroup struct {
	LogGroupARN *string `json:"logGroupARN,omitempty"`
}

type ExecutionListItem struct {
	ExecutionARN    *string      `json:"executionARN,omitempty"`
	Name            *string      `json:"name,omitempty"`
	StartDate       *metav1.Time `json:"startDate,omitempty"`
	StateMachineARN *string      `json:"stateMachineARN,omitempty"`
	StopDate        *metav1.Time `json:"stopDate,omitempty"`
}

type ExecutionStartedEventDetails struct {
	RoleARN *string `json:"roleARN,omitempty"`
}

type HistoryEvent struct {
	Timestamp *metav1.Time `json:"timestamp,omitempty"`
}

type LambdaFunctionScheduledEventDetails struct {
	Resource *string `json:"resource,omitempty"`
}

type LogDestination struct {
	CloudWatchLogsLogGroup *CloudWatchLogsLogGroup `json:"cloudWatchLogsLogGroup,omitempty"`
}

type LoggingConfiguration struct {
	Destinations         []*LogDestination `json:"destinations,omitempty"`
	IncludeExecutionData *bool             `json:"includeExecutionData,omitempty"`
	Level                *string           `json:"level,omitempty"`
}

type MapIterationEventDetails struct {
	Name *string `json:"name,omitempty"`
}

type StateEnteredEventDetails struct {
	Name *string `json:"name,omitempty"`
}

type StateExitedEventDetails struct {
	Name *string `json:"name,omitempty"`
}

type StateMachineListItem struct {
	CreationDate    *metav1.Time `json:"creationDate,omitempty"`
	Name            *string      `json:"name,omitempty"`
	StateMachineARN *string      `json:"stateMachineARN,omitempty"`
	Type            *string      `json:"type_,omitempty"`
}

type Tag struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

type TaskFailedEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskScheduledEventDetails struct {
	Region       *string `json:"region,omitempty"`
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskStartFailedEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskStartedEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskSubmitFailedEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskSubmittedEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskSucceededEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TaskTimedOutEventDetails struct {
	Resource     *string `json:"resource,omitempty"`
	ResourceType *string `json:"resourceType,omitempty"`
}

type TracingConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}
